using System.Collections;
using UnityEngine;
using UnityEngine.AI;

namespace ArcherVR
{
    public enum EnemyTier { Basic, Advanced, Boss }

    /// <summary>
    /// Enemy brain: walks across the NavMesh to a point at the foot of the tower,
    /// then keeps hitting the tower until it dies (Figma: "mobs run into a building
    /// and automatically start hitting it"). Drives an Animator if the model has
    /// Walk / Attack / Die / Idle states, otherwise falls back to a simple bob.
    /// </summary>
    [RequireComponent(typeof(NavMeshAgent))]
    [RequireComponent(typeof(Health))]
    public class EnemyController : MonoBehaviour
    {
        [Header("Stats")]
        public EnemyTier tier = EnemyTier.Basic;
        public float moveSpeed = 2.2f;
        public float attackDamage = 4f;
        public float attackInterval = 1.5f;
        public bool canAttack = true;
        [Tooltip("Each enemy rolls a random speed between moveSpeed × (1 - this) and × (1 + this), " +
                 "so a crowd spreads out into sprinters and stragglers.")]
        [Range(0f, 0.9f)] public float speedVariation = 0.45f;

        /// <summary>This enemy's rolled speed multiplier (1 = average).</summary>
        public float SpeedMultiplier { get; private set; } = 1f;

        [Header("Animator state names (generated by Archer VR > Build)")]
        public string walkState = "Walk";
        public string attackState = "Attack";
        public string dieState = "Die";
        public string idleState = "Idle";

        [Header("Audio (optional)")]
        public AudioClip attackSfx;
        public AudioClip deathSfx;

        [Header("Scripted march (S1 Exposition)")]
        [Tooltip("If set, the enemy walks to haltPoint on Start and waits there without attacking.")]
        public bool marchOnStart;
        public Vector3 haltPoint;

        [Header("Fallback motion when the model has no animations")]
        public Transform model;

        /// <summary>Raised once when this enemy dies.</summary>
        public System.Action<EnemyController> Died;

        enum State { Moving, Attacking, Idle, Dead }

        NavMeshAgent agent;
        Health health;
        Animator anim;
        AudioSource audioSrc;
        TowerHealth tower;
        Vector3 destination;
        bool hasDestination;
        bool pathSet;
        float nextAttack;
        string currentAnimState;
        bool hasAnimations;
        State state = State.Idle;
        float bobSeed;
        Vector3 modelBaseLocalPos;

        public bool IsDead => state == State.Dead;

        void Awake()
        {
            agent = GetComponent<NavMeshAgent>();
            health = GetComponent<Health>();
            anim = GetComponentInChildren<Animator>();
            audioSrc = GetComponent<AudioSource>();
            if (anim != null) anim.applyRootMotion = false;
            health.onDied.AddListener(OnDied);
            bobSeed = Random.value * 10f;
            if (model == null && transform.childCount > 0) model = transform.GetChild(0);
            if (model != null) modelBaseLocalPos = model.localPosition;

            hasAnimations = anim != null && anim.runtimeAnimatorController != null &&
                            anim.HasState(0, Animator.StringToHash(walkState));
        }

        void Start()
        {
            SpeedMultiplier = Random.Range(1f - speedVariation, 1f + speedVariation);
            agent.speed = moveSpeed * SpeedMultiplier;
            // Speed the walk cycle up/down to match so fast enemies don't look like they're skating.
            if (anim != null) anim.speed = Mathf.Lerp(1f, SpeedMultiplier, 0.8f);
            if (marchOnStart) Init(null, haltPoint, false);
        }

        /// <summary>Called by the WaveManager right after spawning.</summary>
        public void Init(TowerHealth targetTower, Vector3 attackPoint, bool attack)
        {
            tower = targetTower;
            canAttack = attack;
            destination = attackPoint;
            hasDestination = true;
            pathSet = false;
            state = State.Moving;
            Play(walkState);
        }

        void Update()
        {
            if (state == State.Dead) return;

            if (!agent.isOnNavMesh)
            {
                if (NavMesh.SamplePosition(transform.position, out var hit, 25f, NavMesh.AllAreas))
                    agent.Warp(hit.position);
                else
                    return;
            }

            switch (state)
            {
                case State.Moving:
                    if (hasDestination && !pathSet)
                    {
                        agent.isStopped = false;
                        agent.SetDestination(destination);
                        pathSet = true;
                    }
                    if (pathSet && !agent.pathPending && agent.remainingDistance <= agent.stoppingDistance + 0.35f)
                        Arrive();
                    break;

                case State.Attacking:
                    if (tower == null || tower.IsDestroyed)
                    {
                        GoIdle();
                        break;
                    }
                    Face(tower.transform.position);
                    if (Time.time >= nextAttack)
                    {
                        nextAttack = Time.time + attackInterval;
                        Play(attackState, true);
                        tower.TakeDamage(attackDamage, transform.position + transform.forward * 0.6f + Vector3.up);
                        if (attackSfx != null && audioSrc != null) audioSrc.PlayOneShot(attackSfx);
                    }
                    break;
            }

            KeepLooping();
            if (!hasAnimations) FallbackMotion();
        }

        void Arrive()
        {
            agent.isStopped = true;
            if (canAttack && tower != null && !tower.IsDestroyed)
            {
                state = State.Attacking;
                nextAttack = Time.time + Random.Range(0.2f, 0.8f);
            }
            else
            {
                GoIdle();
            }
        }

        void GoIdle()
        {
            state = State.Idle;
            if (agent.isOnNavMesh) agent.isStopped = true;
            Play(idleState);
        }

        void Face(Vector3 target)
        {
            var dir = target - transform.position;
            dir.y = 0f;
            if (dir.sqrMagnitude < 0.001f) return;
            transform.rotation = Quaternion.Slerp(transform.rotation, Quaternion.LookRotation(dir), Time.deltaTime * 5f);
        }

        void OnDied()
        {
            if (state == State.Dead) return;
            state = State.Dead;
            if (agent.isOnNavMesh) agent.isStopped = true;
            agent.enabled = false;
            foreach (var c in GetComponentsInChildren<Collider>()) c.enabled = false;
            if (deathSfx != null && audioSrc != null) audioSrc.PlayOneShot(deathSfx);

            if (hasAnimations && anim.HasState(0, Animator.StringToHash(dieState)))
                Play(dieState, true);
            else
                StartCoroutine(ToppleOver());

            Died?.Invoke(this);
            Destroy(gameObject, 4f);
        }

        IEnumerator ToppleOver()
        {
            var start = transform.rotation;
            var end = start * Quaternion.Euler(-90f, 0f, 0f);
            for (float t = 0; t < 1f; t += Time.deltaTime * 2.5f)
            {
                transform.rotation = Quaternion.Slerp(start, end, t);
                yield return null;
            }
        }

        void Play(string stateName, bool restart = false)
        {
            if (anim == null || anim.runtimeAnimatorController == null || string.IsNullOrEmpty(stateName)) return;
            int hash = Animator.StringToHash(stateName);
            if (!anim.HasState(0, hash)) return;
            if (currentAnimState == stateName && !restart) return;
            anim.CrossFadeInFixedTime(hash, 0.15f, 0, 0f);
            currentAnimState = stateName;
        }

        // Clips that live inside FBX files may not be set to loop; restart them by hand.
        void KeepLooping()
        {
            if (anim == null || anim.runtimeAnimatorController == null) return;
            if (currentAnimState != walkState && currentAnimState != idleState) return;
            if (anim.IsInTransition(0)) return;
            var info = anim.GetCurrentAnimatorStateInfo(0);
            if (!info.loop && info.normalizedTime >= 1f)
                anim.Play(Animator.StringToHash(currentAnimState), 0, 0f);
        }

        void FallbackMotion()
        {
            if (model == null) return;
            float t = Time.time * 8f * SpeedMultiplier + bobSeed;
            float bob = state == State.Moving ? Mathf.Abs(Mathf.Sin(t)) * 0.12f : 0f;
            float lunge = state == State.Attacking ? Mathf.Max(0f, Mathf.Sin((Time.time - nextAttack + attackInterval) * 6f)) * 0.3f : 0f;
            model.localPosition = modelBaseLocalPos + new Vector3(0f, bob, lunge);
        }
    }
}
